name: addS3BucketAWS
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List of s3 buckets
      - uses: actions/checkout@main
        run:
          # aws s3 mb s3://$AWS_S3_BUCKET_NAME
          # aws s3 rb s3://s3bucket-from-github
          aws s3 ls
          
      - name: Deleting s3 buckets
      - uses: actions/checkout@main
        run:
          aws s3 rb s3://cf-templates-9tnu5ds575mw-ap-south-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_DEFAULT_REGION: 'ap-south-1'
